openapi: 3.0.1
info:
  title: Service 
  description: Service REST API
  version: "0.1"
servers:
- url: /
paths:
  /comments:
    get:
      summary: Get all comments
      operationId: app.getAllComments
      responses:
        200:
          description: All the comments
    post:
      summary: Create a new comment
      operationId: app.createComment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        201:
          description: The created comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        500:
          description: Internal server error

components:
  schemas:
    Error:
      type: object
      properties:
        type:
          type: string
          description: Error type
          example: about:blank
        title:
          type: string
          description: Error name
          example: Bad Request
        status:
          type: integer
          description: Error status code
          example: about:blank
        detail:
          type: string
          description: Error description
          example: None is not of type 'string'
    Comment:
      type: object
      required:
        - author
        - text
      properties:
        id:
          type: string
          description: Comment id
          example: about:blank
        author:
          type: string
          description: Comment author
          example: D. Adams
        text:
          type: string
          description: Comment text
          example: The answer is 42
        