openapi: 3.0.1
info:
  title: Service 
  description: Service REST API
  version: "0.1"
servers:
- url: /
paths:
  /results:
    get:
      summary: Get the elections results
      operationId: app.results
      responses:
        200:
          description: The elections results
            
        400:
          description: Elections in progress
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
  /candidates:
    get:
      summary: Get the candidates
      operationId: app.candidates
      responses:
        200:
          description: The candidates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Candidate'
        500:
          description: An error occured
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'

  /candidates/{id}:
    get:
      summary: Get the candidate
      operationId: app.candidate
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: The candidate
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Candidate'
        500:
          description: An error occured
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
  /vote:
    post:
      summary: Vote for a candidate
      operationId: app.vote
      parameters:
        - in: header
          name: Auth-Token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vote'
      responses:
        201:
          description: The vote was registered
        400:
          description: Invalid vote
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
        401:
          description: Invalid Token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: An error occured
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        type:
          type: string
          description: Error type
          example: about:blank
        title:
          type: string
          description: Error name
          example: Bad Request
        status:
          type: integer
          description: Error status code
          example: about:blank
        detail:
          type: string
          description: Error description
          example: None is not of type 'string'
    Candidate:
      type: object
      properties:
        firstname:
          minLength: 1
          type: string
          description: Candidate's firstname
          example: "Giuseppe"
        lastname:
          minLength: 1
          type: string
          description: Candidate's lastname
          example: "Garibaldi"
        party:
          type: string
          description: Candidate's party
          example: "The Party"
        id:
          minLength: 1
          type: string
          description: Candidate ID
          example: "1234567890"
    Vote:
      type: object
      required:
        - elector_id
        - candidate_id
      properties:
        elector_id:
          minLength: 1
          type: string
          description: Elector ID
          example: "1234567890"
        candidate_id:
          minLength: 1
          type: string
          description: Candidate ID
          example: "1234567890"
 

